String.implement({format:function(){if(arguments.length==0)return this;var a=arguments;return this.replace(/{(\d+)?}/g,function(c,d){return a[d.toInt()]||""})}});
var Scroller=new Class({Implements:[Events,Options],options:{area:20,velocity:1,onChange:function(a,c){this.element.scrollTo(a,c)}},initialize:function(a,c){this.setOptions(c);this.element=$(a);this.listener=typeOf(this.element)!="element"?$(this.element.getDocument().body):this.element;this.timer=null;this.coord=this.getCoords.bind(this)},start:function(){this.listener.addEvent("mousemove",this.coord)},stop:function(){this.listener.removeEvent("mousemove",this.coord);this.timer=clearInterval(this.timer)},
getCoords:function(a){this.page=this.listener.get("tag")=="body"?a.client:a.page;if(!this.timer)this.timer=this.scroll.periodical(50,this)},scroll:function(){var a=this.element.getSize(),c=this.element.getScroll(),d=this.element.getPosition(),b={x:0,y:0},e;for(e in this.page)if(this.page[e]<this.options.area+d[e]&&c[e]!=0)b[e]=(this.page[e]-this.options.area-d[e])*this.options.velocity;else if(this.page[e]+this.options.area>a[e]+d[e]&&a[e]+a[e]!=c[e])b[e]=(this.page[e]-a[e]+this.options.area-d[e])*
this.options.velocity;if(b.y||b.x)this.fireEvent("change",[c.x+b.x,c.y+b.y])}}),DragDropPlus=new Class({Implements:[Options,Events],options:{ddScope:window},initialize:function(a,c,d){this.dragSelecterString=a;this.dropSelecterString=c;this.drags=$$(a);this.drops=$$(c);this.setOptions(d);if(this.options.ddScope)this.winScroll=new Scroller(this.options.ddScope,{velocity:1});if(this.drag_operate_box=$("drag_operate_box")){this.drag_operate_box.store("lock",false);this.drag_handle_box=this.drag_operate_box.getElement(".drag_handle_box");
this.dobFx=new Fx.Morph(this.drag_operate_box,{fps:50,duration:200,link:"cancel"});this.dragSign=$("drag_ghost_box").inject(document.body);this.initDOBBase(this.drops);this.initDrags(this.drags);this.initDrops(this.drops)}},checkEmptyDropPanel:function(a){if(a&&a.hasClass(this.dropSelecterString.substring(1,this.dropSelecterString.length)))if(a.getElement(this.dragSelecterString))a.getElement(".empty_drop_box")&&a.getElement(".empty_drop_box").destroy();else if(!a.getElement(".empty_drop_box")){(new Element("div.empty_drop_box")).set("text",
LANG_dragdropplus.empty_box).inject(a);if(this.dragmoveInstance){a.store("droppanel",true);this.dragmoveInstance.droppables.include(a)}}},dragLeave:function(){},dargInject:function(a,c){var d=this.dragging;if(d){var b="inside";c.retrieve("droppanel")||(b=d.getAllPrevious().contains(c)?"before":"after");d.inject(c,b);this.checkEmptyDropPanel(a.retrieve("droped"));this.checkEmptyDropPanel(c);a.store("droped",c);this.dragSign.setStyles(d.getCoordinates())}},getDropables:function(){var a=this.dragging;
return Array.from(this.drags).erase(a).combine(this.drops.filter(function(c){if(c.getElement(this.dragSelecterString)){c.store("droppanel",false);return false}else{c.store("droppanel",true);return true}}.bind(this)))},initDOBBase:function(a){var c=this.drag_operate_box,d=this.drag_handle_box,b=this;if(a){var e=this.winScroll;d.getElement(".dhb_edit").addEvent("click",function(g){g.stop();this.fireEvent("onEdit",[c.retrieve("drag")],this)}.bind(this));d.getElement(".dhb_del").addEvent("click",function(g){g.stop();
this.fireEvent("onDelete",[c.retrieve("drag")],this)}.bind(this));d.getElement(".dhb_title").addEvents({mousedown:function(g){b.dragging=c.retrieve("drag");c.setStyle("left",c.getPosition().x+10);c.store("droped",b.dragging.getParent(b.dropSelecterString));c.store("lock",true);b.dragmoveInstance=new Drag.Move(c,{handle:this,droppables:b.getDropables.call(b),snap:0,preventDefault:true,onEnter:b.dargInject.bind(b),onStart:function(){b.dragSign.setStyles(Object.append(b.dragging.getCoordinates(),{visibility:"visible"}));
e&&e.start()},onComplete:function(){e&&e.stop();b.dobFx.start(b.dragging.getCoordinates()).chain(function(){this.element.store("lock",false)})}});b.dragmoveInstance.start(g)},mouseup:function(g){b.dragmoveInstance.stop(g);b.dragmoveInstance.cancel(g);b.dragmoveInstance.detach();b.dragSign&&b.dragSign.setStyle("visibility","hidden")}})}},initDrags:function(a){var c=this;a.each(function(d){c.fireEvent("onInitDrags",[d,a],this);d.addEvents({mouseenter:function(){var b=c.drag_operate_box;if(!b.retrieve("lock")){b.getElement(".dhb_title").set("html",
d.get("title")||"&nbsp;");b.setStyle("visibility","visible");b.store("drag",this);b=d.getCoordinates();b=Object.append(b,{height:b.height.limit(26,Number.MAX_VALUE)-2,width:b.width.limit(130,Number.MAX_VALUE)});c.dobFx.start(b)}}});d.getElements("a").removeEvents().addEvent("click",function(b){b.stop()});d.getElements("form").removeEvents().addEvent("submit",function(b){b.stop()})})},initDrops:function(a){var c=this;a.each(function(d){c.checkEmptyDropPanel(d);c.fireEvent("onInitDrops",[d,a],this)})}}),
Widgets=new Class({Extends:DragDropPlus,initialize:function(a,c,d){this.parent(a,c,d);this.drags.each(function(b){b.getProperty("ishtml")&&b.getElement(".content-html").set("html",b.getElement(".content-textarea").get("value"))})},inject:function(a,c){this.addWidget(this.curEl,a,c?c:this.theme)},ghostDrop:function(a,c){this.drag_operate_box.setStyle("visibility","hidden").store("lock",true);$("tempDropBox")&&$("tempDropBox").destroy();this.tempDropBox=(new Element("div",{id:"tempDropBox"})).inject(document.body);
try{this.drops.each(function(b,e){if(b){var g=this,h=b.getCoordinates();if(h.height>5&&h.width>5){h.height-=5;h.width-=5}(new Element("div",{"class":"widgets_drop_ghost",styles:Object.merge(h,{opacity:0.3}),text:"["+(e+1)+"]",title:LANG_shopwidgets.dropghostTitle1+a.name+LANG_shopwidgets.dropghostTitle2})).addEvents({mouseover:function(){this.addClass("widgets_drop_ghost_on")},mouseleave:function(){this.removeClass("widgets_drop_ghost_on")},click:function(){g.tempDropBox.empty();g.addWidget(b,a,c);
g.drag_operate_box.store("lock",false)}}).inject(g.tempDropBox)}},this)}catch(d){alert(JSON.encode(d))}document.body.addEvent("contextmenu",function(b){b.stop();$("tempDropBox")&&$("tempDropBox").destroy();this.drag_operate_box.store("lock",false);document.body.removeEvent("contextmenu",arguments.callee)}.bind(this))},copyWidgets:function(){},addWidget:function(a,c,d){this.curdialog=new top.Dialog(top.SHOPADMINDIR+"index.php?&app=site&ctl=admin_theme_widget&act=do_add_widgets&widgets="+c.name+"&widgets_app="+
c.app+"&widgets_theme="+c.theme+"&theme="+d,{modal:true,title:LANG_shopwidgets.addWidget+(c.label||""),ajaxoptions:{render:false},width:0.7,height:0.7});this.curDrop=a},editWidget:function(a){var c={modal:true,title:LANG_shopwidgets.editWidget+(a.label||a.title),ajaksable:false,width:0.7,height:0.7};this.curWidget=$(a);if(a.get("ishtml"))return this.curdialog=new top.Dialog(top.SHOPADMINDIR+"index.php?ctl=content/pages&act=editHtml",Object.merge(c,{ajaksable:true,ajaxoptions:{method:"post",data:"htmls="+
encodeURIComponent(a.getElement(".content-html").get("html").clean().trim())},title:LANG_shopwidgets.editHTML}));return this.curdialog=new top.Dialog(top.SHOPADMINDIR+"index.php?app=site&ctl=admin_theme_widget&act=do_edit_widgets&widgets_id="+a.get("widgets_id")+"&theme="+a.get("widgets_theme"),c)},saveAll:function(){var a=[],c={};this.drops.each(function(d){d.getElements(".shopWidgets_box").each(function(b){a.push("widgets[{widgetsId}]={baseFile}:{baseSlot}:{baseId}".substitute({widgetsId:b.get("widgets_id"),
baseFile:this.bf,baseSlot:this.bs,baseId:this.bi}));if(b.get("ishtml")){var e=b.getElement(".content-html");a.push("html[{widgetsId}]={htmls}".substitute({widgetsId:b.get("widgets_id"),htmls:encodeURIComponent(e.get("html"))}))}},{mce:this.mce,bf:d.get("base_file"),bs:d.get("base_slot"),bi:d.get("base_id")});c[d.get("base_file")]=1}.bind(this));for(f in c)a.push("files[]={file}".substitute({file:f}));(new Request({url:top.SHOPADMINDIR+"index.php?app=site&ctl=admin_theme_widget&act=save_all",method:"post",
data:a.join("&"),onRequest:function(){new top.MessageBox(LANG_shopwidgets.saving)},onSuccess:function(d){try{d=JSON.decode(d);for(dom in d)$(dom)&&d[dom]&&$(dom).setProperty("widgets_id",d[dom]);top.MessageBox.success(LANG_shopwidgets.saveSuccess)}catch(b){top.MessageBox.error(LANG_shopwidgets.saveError+b.message)}}})).send()}});
window.addEvent("domready",function(){this.shopWidgets=new Widgets(".shopWidgets_box",".shopWidgets_panel",{onEdit:function(a){shopWidgets.editWidget(a)},onDelete:function(a){if(confirm(LANG_shopwidgets.comfirmDel)){var c=this.drag_operate_box,d=this;c.setStyle("visibility","hidden").store("lock",true);var b=a.getParent();(new Fx.Tween(a)).start("opacity",0).chain(function(){a.destroy();c.store("lock",false);d.checkEmptyDropPanel(b)})}}})});