(function(){if(!(window.google&&google.gears)){var c=null;if(typeof GearsFactory!="undefined")c=new GearsFactory;else try{c=new ActiveXObject("Gears.Factory");c.getBuildInfo().indexOf("ie_mobile")!=-1&&c.privateSetGlobalObject(this)}catch(g){if(typeof navigator.mimeTypes!="undefined"&&navigator.mimeTypes["application/x-googlegears"]){c=document.createElement("object");c.style.display="none";c.width=0;c.height=0;c.type="application/x-googlegears";document.documentElement.appendChild(c)}}if(c){window.google||
(google={});if(!google.gears)google.gears={factory:c}}}})();
(function(){BrowserStore=new Class({initialize:function(){this.storage=c.init()||h.init()||g.init()||j.init()||false||{};return this},set:function(a,b){this.storage.setStorage=this.storage.setStorage||function(){};this.storage.setStorage(a,b?JSON.encode(b):null);return this},get:function(a,b){this.storage.getStorage=this.storage.getStorage||function(){};this.storage.getStorage(a,b)},remove:function(a){if(!a||!this.storage)return false;this.storage.removeStorage=this.storage.removeStorage||function(){};
this.storage.removeStorage(a);return this},clear:function(){if(!this.storage)return false;this.storage.clearStorage=this.storage.clearStorage||function(){};this.storage.clearStorage();return this}});var c={name:"Google Gears",init:function(){var a;try{if(a=google.gears.factory.create("beta.database")){a.open("database-shopex_viewstatus");a.execute("create table if not exists status (skey text, sval text)");this.db=a;this.Master="gears"}else return false}catch(b){return false}return this},setStorage:function(a,
b){var d=this.db.execute("select * from status where skey=?",[a]);if(d.isValidRow()){this.db.execute("update status set sval=? where skey=?",[b,a]);d.close()}else this.db.execute("insert into status values (?,?)",[a,b])},getStorage:function(a,b){var d=this.db.execute("select * from status where skey=?",[a]);d.isValidRow()?b(d.field(1)):b();d.close()},removeStorage:function(a){this.db.execute("delete from status where skey=?",[a])},clearStorage:function(){this.db.execute("drop table status")}},g={name:"globalStorage",
init:function(){if(!window.globalStorage)return false;this._storage=globalStorage[location.hostname];return this},setStorage:function(a,b){this._storage.setItem(a,b);return true},getStorage:function(a,b){var d=this._storage.getItem(a);b(d?d.value:null)},removeStorage:function(a){this._storage.removeItem(a);return true},clearStorage:function(){if(this._storage.clear)this._storage.clear();else for(i in this._storage)this._storage[i].value&&this.remove(i);return true}},j={name:"userdata",init:function(){this.Master=
"ie6+";if(!Browser.ie)return false;this._storage=(new Element("span")).setStyles({display:"none",behavior:"url('#default#userData')"}).inject(document.body);return this},setStorage:function(a,b){this._storage.setAttribute(a,b);this._storage.save("shopEX_VS");return true},getStorage:function(a,b){this._storage.load("shopEX_VS");b(this._storage.getAttribute(a))},removeStorage:function(a){this._storage.removeAttribute(a);this._storage.save("shopEX_VS");return true},clearStorage:function(){var a=new Date;
a.setMinutes(a.getMinutes()-1);this._storage.expires=a.toUTCString();this._storage.save("shopEX_VS");this._storage.load("shopEX_VS");return true}},h={name:"openDatabase",init:function(){if(!window.openDatabase)return false;this._storage=window.openDatabase("viewState","1.0","ShopEX48 ViewState Storage",2E4);this._createTable();return this},setStorage:function(a,b){this._storage.transaction(function(d){d.executeSql("SELECT v FROM SessionStorage WHERE k = ?",[a],function(f,e){e.rows.length>0?f.executeSql("UPDATE SessionStorage SET v = ?  WHERE k = ?",
[b,a]):f.executeSql("INSERT INTO SessionStorage (k, v) VALUES (?, ?)",[a,b])})});return true},getStorage:function(a,b){this._storage.transaction(function(d){v=d.executeSql("SELECT v FROM SessionStorage WHERE k = ?",[a],function(f,e){if(e.rows.length>0)return b(e.rows.item(0).v);b(null)})})},removeStorage:function(a){this._storage.transaction(function(b){b.executeSql("DELETE FROM SessionStorage WHERE k = ?",[a])});return true},clearStorage:function(){this._storage.transaction(function(a){a.executeSql("DROP TABLE SessionStorage",
[])});return true},_createTable:function(){this._storage.transaction(function(a){a.executeSql("SELECT COUNT(*) FROM SessionStorage",[],function(){},function(b){b.executeSql("CREATE TABLE SessionStorage (k TEXT, v TEXT)",[],function(){})})})}}})();